# 1. Le module NumPy

Un module est un ensemble de fonctions et de types d'objets (classes). En général, quelqu'un d'autre s'est posé la question que vous vous posez avant vous :)

En particulier, `numpy` est le module de référence pour le calcul numérique et l'algèbre linéaire.

## 1.1. Importer un module

Pour importer un module, on a plusieurs manières, qui vont influencer la manière de s'en servir.

In [1]:
import math

print(math.pi)

3.141592653589793


Parfois, les noms de modules sont un peu longs. On peut les renommer à notre guise.

In [2]:
import math as mt

print(mt.pi)

3.141592653589793


Quand on ne souhaite utiliser qu'une ou deux choses dans le module.

In [3]:
from math import pi

print(pi)

3.141592653589793


*Cette dernière manière n'est généralement pas préférée*, car on importe plein de noms de variables sans trop savoir lesquels...

In [4]:
from math import *

print(pi)

3.141592653589793


## <font color=blue>1.2. Exercice</font>

Importer le module `numpy` en le renommant `np`.

In [4]:
import numpy as np

## 1.3. Les numpy arrays

Ils vont nous permettre d'aller au-delà des listes, et notamment de *nous faciliter (et nous accélérer) les opérations d'algèbre*.

### 1.3.1. Les basiques

In [5]:
length = [1.73, 1.85, 1.92]

length ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [7]:
np_length = np.array([ 1.73,  1.85,  1.92])
np_length

array([ 1.73,  1.85,  1.92])

In [8]:
type(np_length)

numpy.ndarray

In [9]:
np_length ** 2

array([ 2.9929,  3.4225,  3.6864])

Les calculs se font bien sur élément par élément !

### 1.3.2. Quelques warnings

**Attention : les numpy arrays ne contiennent qu'un type d'élément !**

In [10]:
np.array([1, True, 'ab'])

array(['1', 'True', 'ab'],
      dtype='<U11')

**Attention : l'opération `+` n'a pas le même sens (du tout !) pour une liste ou pour un numpy array !**

In [11]:
[1, 2, 3] + [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [12]:
np.array([1, 2, 3]) + np.array([1, 2, 3])

array([2, 4, 6])

### 1.3.3. Récupérer des éléments

Ca fonctionne pareil !

In [13]:
np_length[-1]

1.9199999999999999

Mais c'est aussi beaucoup plus puissant !

In [14]:
np_length > 1.8

array([False,  True,  True], dtype=bool)

In [15]:
np_length[np_length > 1.8]

array([ 1.85,  1.92])

In [9]:
np.random.random(size=10)

array([0.62539334, 0.02365988, 0.59882614, 0.20412977, 0.99996749,
       0.74208382, 0.20173611, 0.04147811, 0.44424789, 0.7764479 ])

In [10]:
np.random.normal(size=10)

array([ 0.20086664,  0.69423067,  0.30815942,  0.0315489 ,  1.78624542,
       -0.73409083,  0.1090614 , -0.29042409, -0.21718568,  0.00689688])

In [8]:
for i in range(10):
    x = np.random.random(size=1000)
    print(len(x[x > 0.9]))

98
102
100
90
96
103
99
101
102
110


### <font color=blue> 1.3.4. Exercice</font>

Calculez d'un coup l'IMC de plusieurs personnes :
* Max : 1m76 et 82kg,
* Sophie : 1m63 et 68kg,
* Franck : 1m92 et 110 kg.

In [17]:
heights = np.array([1.76, 1.63, 1.92])
weights = np.array([82, 68, 110])

In [18]:
weights / heights ** 2

array([ 26.47210744,  25.59373706,  29.83940972])

Maintenant faites-le en définissant une fonction `imc`.

In [19]:
def imc(h, w):
    return w / h ** 2

In [20]:
imc(heights, weights)

array([ 26.47210744,  25.59373706,  29.83940972])

# 1.4. Les 2D numpy arrays

Comment faire si on veut définir une matrice ?

## 1.4.1. Les basiques

In [13]:
np_2d = np.array([[1.76, 1.63, 1.92],
                  [  82,   68,  110]])
print(np_2d, type(np_2d))

[[  1.76   1.63   1.92]
 [ 82.    68.   110.  ]] <class 'numpy.ndarray'>


In [15]:
np_2d = np.random.random(size=[2, 3])
print(np_2d)

[[0.39269735 0.55804526 0.54665288]
 [0.57809638 0.31554042 0.76142438]]


In [16]:
type(np_2d)

numpy.ndarray

In [17]:
np_2d.shape

(2, 3)

## 1.4.2. Accéder à un élément

Plein de fonctions pratiques mais il ne faut pas s'y perdre entre les lignes et les colonnes !

In [18]:
np_2d

array([[0.39269735, 0.55804526, 0.54665288],
       [0.57809638, 0.31554042, 0.76142438]])

In [19]:
np_2d[0]

array([0.39269735, 0.55804526, 0.54665288])

In [20]:
np_2d[0][1]

0.5580452559348973

In [21]:
np_2d[0, 1]

0.5580452559348973

In [22]:
np_2d[0, [0, 1]]

array([0.39269735, 0.55804526])

In [23]:
np_2d[:, 1:3]

array([[0.55804526, 0.54665288],
       [0.31554042, 0.76142438]])

## 1.4. Générer des données aléatoires

NumPy contient beaucoup de générateurs de nombres aléatoires, pour différentes lois.

### 1.4.1. Loi uniforme [0, 1]

In [24]:
np.random.random()

0.997586957508215

In [25]:
np.random.random()

0.9681343880597163

In [26]:
np.random.random(10)

array([0.03590151, 0.01558055, 0.17522991, 0.58963526, 0.41061559,
       0.47367808, 0.32124262, 0.52747549, 0.93061133, 0.57181766])

### 1.4.2. Loi binomiale

In [28]:
np.random.binomial(1, 0.5, size=10)

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 1])

In [29]:
type(np.random.binomial(1, .5, size=10))

numpy.ndarray

In [36]:
np.mean(np.random.binomial(1, .5, size=100000))

0.50017

In [36]:
np.random.binomial(3, .5, 100)

array([1, 0, 0, 2, 1, 0, 1, 1, 1, 1, 1, 2, 2, 2, 0, 1, 2, 2, 2, 2, 2, 2,
       1, 1, 0, 2, 2, 2, 0, 3, 2, 3, 1, 0, 3, 1, 2, 1, 1, 2, 2, 2, 1, 2,
       2, 2, 0, 3, 2, 1, 2, 1, 0, 0, 3, 0, 2, 2, 2, 2, 1, 1, 1, 2, 2, 3,
       2, 1, 2, 1, 3, 2, 3, 2, 2, 1, 3, 1, 1, 1, 1, 3, 2, 2, 1, 3, 3, 2,
       2, 1, 1, 3, 3, 1, 2, 1, 1, 2, 0, 2])

In [37]:
np.mean(np.random.binomial(3, .5, 10000) == 3)

0.1256

### 1.4.3. Loi normale

In [38]:
np.random.normal(size=10)

array([ 1.63962666, -0.41488732, -0.05165146,  0.79368367, -0.31977955,
       -0.33083063, -1.51798735, -0.30489985,  0.23108175,  1.14423407])

In [39]:
np.random.normal(size=[2, 3])

array([[ 0.59234988, -1.45930759,  0.18299148],
       [-1.44375942, -0.19981278,  1.80807527]])

### <font color=blue>1.4.4. Exercice</font>

Lancez une pièce 100 fois et vérifier combien vous avez de "pile".

Pour cela vous pourrez utiliser :
* la fonction `np.sum` qui s'applique à un NumPy Array (ou à une liste).
* ou bien la sélection par condition du type `mon_array >= 3.2`

In [41]:
np.sum(np.random.binomial(1, .5, size=100) == 0)

48

In [44]:
nb_expes = 10000
cnt = 0
for i in range(nb_expes):
    res = np.sum(np.random.binomial(1, .5, size=100) == 0)
    if res == 36:
        cnt += 1

print(f"proba : {cnt/nb_expes}")

proba : 0.0017


## 1.5. Algèbre linéaire

Bien sûr, on peut multiplier une valeur par un vecteur. Et NumPy est d'ailleurs fait pour être efficace avec ce type d'opérations.

Au passage, utilisons la fonction `help`, qui s'applique à n'importe quelle fonction ou méthode.

### 1.5.1. Multiplication matricielle

In [47]:
help(np.array(1).dot)

Help on built-in function dot:

dot(...) method of numpy.ndarray instance
    a.dot(b, out=None)
    
    Dot product of two arrays.
    
    Refer to `numpy.dot` for full documentation.
    
    See Also
    --------
    numpy.dot : equivalent function
    
    Examples
    --------
    >>> a = np.eye(2)
    >>> b = np.ones((2, 2)) * 2
    >>> a.dot(b)
    array([[ 2.,  2.],
           [ 2.,  2.]])
    
    This array method can be conveniently chained:
    
    >>> a.dot(b).dot(b)
    array([[ 8.,  8.],
           [ 8.,  8.]])



In [48]:
A = np.random.normal(size=[2, 3])
print(A)

[[-0.22347891  0.49697622 -0.02505081]
 [-1.50092959 -0.33407061  0.10548562]]


In [49]:
b = np.random.normal(size=3)
print(b)

[ 0.67533743 -0.09333498 -0.50608335]


In [50]:
A.dot(b)

array([-0.18463114, -1.03583797])

### 1.5.2. Décomposition et valeurs propres

Facile de calculer les valeurs et vecteurs propres d'une matrice !

In [51]:
A = np.array([[1, 2],
              [3, 4]])

np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

### 1.5.3. Systèmes linéaires

Ou bien de résoudre une équation linéaire *A x = b*.

In [42]:
A = np.array([[3,1], [1,2]])
b = np.array([9,8])

np.linalg.solve(A, b)

array([ 2.,  3.])